from pathlib import Path
p = Path(r"C:/Users/yxu59/files/autumn2025/park/DynamicCalibration/rolled_cusum_modeling_workdoc.md")
text = p.read_text(encoding='utf-8')
anchor = '- `Exact-wCUSUM` and `FixedSupport-wCUSUM` are viable changepoint controllers,\n  but they still pay a predictive penalty relative to `proxy` on the smoother\n  regimes.\n'
insert = '''\n\n### Threshold sensitivity on sudden (2026-04-17)\n\nWe also ran a sudden-only threshold sensitivity sweep for the corrected\n1048-particle wCUSUM controller using:\n\n- thresholds: `0.15, 0.25, 0.50, 1.00`\n- magnitudes: `0.5, 1.0, 2.0, 3.0`\n- seeds: `0..9`\n- methods: `half_refit`, `Proxy-wCUSUM`, `Exact-wCUSUM`, `FixedSupport-wCUSUM`\n\nTemporary orchestration command:\n\n```bash\nconda run -n jumpGP python _tmp_wcusum_threshold_sensitivity_np1048.py\n```\n\nOutputs:\n\n- `figs/wcusum_threshold_sensitivity_20260417_seed10_np1048/threshold_overall_summary.csv`\n- `figs/wcusum_threshold_sensitivity_20260417_seed10_np1048/threshold_alignment_summary.csv`\n- `figs/wcusum_threshold_sensitivity_20260417_seed10_np1048/threshold_sensitivity_overall.png`\n\nMain findings:\n\n- `Proxy-wCUSUM` is quite insensitive in `y`-RMSE across the tested threshold band\n  (`0.8556, 0.8563, 0.8585, 0.8581`), but the detector becomes too conservative\n  at `threshold = 1.0` for weak jumps (`magnitude = 0.5` gives `0.0` mean restarts).\n- `Exact-wCUSUM` and `FixedSupport-wCUSUM` show the expected tradeoff:\n  larger threshold reduces false alarms, but only slightly changes the mean\n  predictive error.\n- Across these four thresholds, `0.25` to `0.50` is the most defensible band:\n  it keeps restart counts near the true `3` changepoints, avoids the obvious\n  under-triggering seen at `1.0` on weak jumps, and is not materially worse than\n  `0.15` on the prediction metrics.\n\nSo if we need to defend the controller choice to a reviewer, the right statement is\nnot that `0.25` is theoretically calibrated, but that the sudden-only sensitivity\nshows a stable operating region around `0.25` to `0.50`, with `1.0` already too\nconservative for smaller jumps.\n'''
if anchor not in text:
    raise SystemExit('anchor not found')
text = text.replace(anchor, anchor + insert, 1)
p.write_text(text, encoding='utf-8')
print('patched threshold sensitivity note')
